#!/bin/sh /etc/rc.common
# "new(er)" style init script
# Look at /lib/functions/service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.

START=71
APP=sysmgr
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start() {
	i2cdetect  -r -y 0 | grep 3c > /dev/null && DISPTYPE=ssd1306_128x64
	i2cdetect  -r -y 0 | grep 27 > /dev/null && DISPTYPE=1602_pcf
        service_start /opt/fmw/bin/$APP --boardtype=$(cat /tmp/BrBoxDevType.txt) --syscfg=$(cat /boot/sysconfig.txt) --disptype=$DISPTYPE
}

stop() {
        service_stop /opt/fmw/bin/$APP
}
