#!/bin/sh /etc/rc.common
# "new(er)" style init script
# Look at /lib/functions/service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.

START=74
APP=apisrv
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
HTTP_PORT=80

start() {
        service_start /opt/fmw/bin/$APP --boardtype=$(cat /tmp/BrBoxDevType.txt) --httpport=$HTTP_PORT
}

stop() {
        service_stop /opt/fmw/bin/$APP
}

