#!/bin/sh /etc/rc.common
# "new(er)" style init script
# Look at /lib/functions/service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.

START=76
APP=bboxsmssrv
APPCLT=bboxsmsclt
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start() {
        service_start /opt/fmw/bin/$APP --boardtype=$(cat /tmp/BrBoxDevType.txt) &
}

stop() {
        /opt/fmw/bin/$APPCLT --shutdown
	sleep 5
}
