#!/bin/sh
#
# Start the BrBox Services
#

case "$1" in
  start)
	echo "Starting BrBox Services..."
	# Start all init scripts in /opt/fmw/etc/init.d
	# executing them in numerical order.
	#
	for i in /opt/fmw/etc/init.d/S7?* ;do

	     # Ignore dangling symlinks (if any).
	     [ ! -f "$i" ] && continue

	     case "$i" in
		*.sh)
		    # Source shell script for speed.
		    (
			trap - INT QUIT TSTP
			set start
			. $i
		    )
		    ;;
		*)
		    # No sh extension, so fork subprocess.
		    $i start
		    ;;
	    esac
	done

	;;
  stop)
	echo -n "Stopping BrBox Services..."
	# Stop all init scripts in /opt/fmw/etc/init.d
	# executing them in reversed numerical order.
	#
	for i in $(ls -r /opt/fmw/etc/init.d/S7?*) ;do

     	# Ignore dangling symlinks (if any).
	     [ ! -f "$i" ] && continue

	     case "$i" in
		*.sh)
		    # Source shell script for speed.
		    (
			trap - INT QUIT TSTP
			set stop
			. $i
		    )
		    ;;
		*)
		    # No sh extension, so fork subprocess.
		    $i stop
		    ;;
	    esac
	done
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

