#BRBOX_LIBADSTTNGS_SOURCE=lib-settings.tar.gz
BRBOX_LIBADSTTNGS_VERSION=0.1
BRBOX_LIBADSTTNGS_SITE_METHOD=local
BRBOX_LIBADSTTNGS_SITE=$(TOPDIR)/../sources/lib/lib-settings
BRBOX_LIBADSTTNGS_INSTALL_STAGING=YES
BRBOX_LIBADSTTNGS_INSTALL_TARGET=YES
$(eval $(cmake-package))
#$(eval $(call CMAKETARGETS,package,brbox_libAdSttngs))

