#!/bin/sh /etc/rc.common
# "new(er)" style init script
# Look at /lib/functions/service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.

START=73
APP=xmproxysrv
APPCLT=xmproxyclt
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

XMPP_FILE_DIR=/etc/xmproxy
XMPP_LOGIN_DATA="$XMPP_FILE_DIR/xmpp-login.txt"
ALIAS_LIST_DATA="$XMPP_FILE_DIR/xmpp-alias-list.txt"
BOT_NAME_DATA="$XMPP_FILE_DIR/xmpp-bot-name.txt"

start() {
	#if login file doesnt exist, then create an empty file(later login data can be filled in)
	if [ ! -f "$XMPP_LOGIN_DATA" ]; then
		mkdir -p $XMPP_FILE_DIR
		touch $XMPP_LOGIN_DATA
	fi
	IFACE_NAME=$(cat /etc/dispsrv/iface-name.txt)
    USB_TETHER=$(ifconfig | grep usb0) #if usb0 network interface exists, then use it
	[ $? = 0 ] && IFACE_NAME="usb0"
	service_start /opt/fmw/bin/$APP --updateurl=/etc/sysupdate_url.txt --iface=$IFACE_NAME --boardtype=$(cat /tmp/BrBoxDevType.txt) --loginfile=$XMPP_LOGIN_DATA --aliaslist=$ALIAS_LIST_DATA --botname=$BOT_NAME_DATA --usbgsm=0 &
}

stop() {
    /opt/fmw/bin/$APPCLT --shutdown
	sleep 5
}
