#!/bin/sh
#
# Start/stop server script
#
CLIENT_NAME=/opt/fmw/bin/xmproxyclt
SERVER_NAME=/opt/fmw/bin/xmproxysrv
DEV_TYPE_FILE=/tmp/BrBoxDevType.txt
XMPP_LOGIN_DATA=/mnt/settings/etc/xmpp.login
start() {
	echo -n "Starting $SERVER_NAME Service: "
	DEV_TYPE=$(cat $DEV_TYPE_FILE)
	$SERVER_NAME --boardtype=$DEV_TYPE --loginfile=$XMPP_LOGIN_DATA &
	echo "OK"
}

stop() {
	echo -n "Stopping $SERVER_NAME Service:  "
	$CLIENT_NAME --shutdown
	sleep 1
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
