#!/bin/sh
#
# Start Gstd-daemon
#
SERVER_NAME=gstd
SERVER_PORT=5000
SERVER_PROTOCOL="-t"
start() {
	echo -n "Starting Gstd-daemon: "
	sysctl -w net.core.rmem_max=98214400	
	mkdir -p /var/log/gstd/
	mkdir -p /var/run/gstd/	
	export DISPLAY=:0;$SERVER_NAME --tcp-base-port=$SERVER_PORT $SERVER_PROTOCOL &
	echo "OK"
}

stop() {
	echo -n "Stopping Gstd-daemon: "
	killall $SERVER_NAME
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

