#!/bin/sh

# we use ifplugd to automatically configure eth0 if a cable is plugged in/out

DAEMON="ifplugd"
PIDFILE="/var/run/$DAEMON.pid"
IFACE="eth0"
ACTION="/etc/ifplugd/ifplugd.action"

start()
{
  echo -n "Starting $DAEMON: "
  start-stop-daemon -b -m -S -q -p $PIDFILE -x /usr/sbin/$DAEMON -- -n -f -M -I -t3 -u5 -d5 -i $IFACE -r "$ACTION"
  status=$?
  if [ "$status" -eq 0 ]; then
    echo "OK"
  else
    echo "FAIL"
  fi
}

stop()
{
  echo -n "Stopping $DAEMON: "
  start-stop-daemon -K -q -p "$PIDFILE"
  status=$?
  if [ "$status" -eq 0 ]; then
    rm -f "$PIDFILE"
    echo "OK"
  else
    echo "FAIL"
  fi
}

case "$1" in
  start|stop)
    "$1";;
  restart)
    stop
    start
    ;;
  *)
    echo "usage $0 {start|stop|restart}"
    ;;
esac

exit 0

