#!/bin/sh

# a watchdog, which will restart asterisk in case of problems

DAEMON="asterisk_wdog"
PIDFILE="/var/run/$DAEMON.pid"

start()
{
  echo -n "Starting $DAEMON: "
  start-stop-daemon -b -m -S -q -p $PIDFILE -x /opt/heatingControl/$DAEMON
  status=$?
  if [ "$status" -eq 0 ]; then
    echo "OK"
  else
    echo "FAIL"
  fi
}

stop()
{
  echo -n "Stopping $DAEMON: "
  start-stop-daemon -K -q -p "$PIDFILE"
  status=$?
  if [ "$status" -eq 0 ]; then
    rm -f "$PIDFILE"
    echo "OK"
  else
    echo "FAIL"
  fi
}

case "$1" in
  start|stop)
    "$1";;
  restart)
    stop
    start
    ;;
  *)
    echo "usage $0 {start|stop|restart}"
    ;;
esac

exit 0

