BRBOX_LIBADDISP_VERSION=0.1
BRBOX_LIBADDISP_SITE_METHOD=local
BRBOX_LIBADDISP_SITE=$(TOPDIR)/../sources/lib/lib-display
BRBOX_LIBADDISP_INSTALL_STAGING=YES
BRBOX_LIBADDISP_INSTALL_TARGET=YES
BRBOX_LIBADDISP_DEPENDENCIES = i2c-tools
$(eval $(cmake-package))

