#ifndef __ADCMN_PORTLIST_H_
#define __ADCMN_PORTLIST_H_

#define ADCMN_PORT_BEGIN     40000
#define ADCMN_PORT_SYSMGR    ADCMN_PORT_BEGIN+1
#define ADCMN_PORT_SMARTEYE  ADCMN_PORT_BEGIN+2
#define ADCMN_PORT_GPIOCTL   ADCMN_PORT_BEGIN+3
#define ADCMN_PORT_BBOXSMS   ADCMN_PORT_BEGIN+4
#define ADCMN_PORT_XMPROXY   ADCMN_PORT_BEGIN+5
#define ADCMN_PORT_APISRV    ADCMN_PORT_BEGIN+6
#define ADCMN_PORT_I2CSRV    ADCMN_PORT_BEGIN+7
#endif
