#ifndef __ADCMN_DEVTYPE_H_
#define __ADCMN_DEVTYPE_H_

#define ADCMN_BOARD_TYPE_TABLE  {"RASPI_A","RASPI_APLUS","RASPI_B","RASPI_BPLUS","RASPI_B2","BAYTRAIL","BAYTRAIL_I210","Unknown","none","\0"}
typedef enum ADCMN_BOARD_TYPE_T
{
	ADCMN_BOARD_TYPE_RASPI_A,
	ADCMN_BOARD_TYPE_RASPI_APLUS,
	ADCMN_BOARD_TYPE_RASPI_B,
	ADCMN_BOARD_TYPE_RASPI_BPLUS,
	ADCMN_BOARD_TYPE_RASPI_B2,
	ADCMN_BOARD_TYPE_BAYTRAIL,
	ADCMN_BOARD_TYPE_BAYTRAIL_I210,
	ADCMN_BOARD_TYPE_UNKNOWN,
	ADCMN_BOARD_TYPE_NONE
}ADCMN_BOARD_TYPE;
typedef struct ADCMN_DEV_INFO_T
{
	ADCMN_BOARD_TYPE BoardType;
}ADCMN_DEV_INFO;

#endif
