#!/bin/sh
#
# Start/stop server script
#
SERVER_NAME=mplaysrv #hotwiresrv
SERVER_PATH=/opt/fmw/bin/
DEV_TYPE_FILE=/tmp/BrBoxDevType.txt
start() {
	echo -n "Starting $SERVER_NAME Service: "
	DEV_TYPE=$(cat $DEV_TYPE_FILE)
	$SERVER_PATH/$SERVER_NAME --boardtype=$DEV_TYPE 1>/dev/null 2>/dev/null &
	echo "OK"
}

stop() {
	echo -n "Stopping $SERVER_NAME Service:  "
	killall $SERVER_NAME
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
