BRBOX_LIBADCMNOLD_VERSION = 0.1
BRBOX_LIBADCMNOLD_SITE_METHOD = local
BRBOX_LIBADCMNOLD_SITE = $(TOPDIR)/../sources/lib/lib-adav-old
BRBOX_LIBADCMNOLD_INSTALL_STAGING = YES
BRBOX_LIBADCMNOLD_INSTALL_TARGET = YES
BRBOX_LIBADCMNOLD_CONF_OPTS=-DAUTO_SVN_VERSION=OFF -DINSTALL_MY_HEADERS=OFF
BRBOX_LIBADCMNOLD_DEPENDENCIES = brbox_libAdSttngs json-c
$(eval $(cmake-package))

