BRBOX_LIBADCMN_VERSION = 0.1
BRBOX_LIBADCMN_SITE_METHOD = local
BRBOX_LIBADCMN_SITE = $(TOPDIR)/../sources/lib/lib-adav
BRBOX_LIBADCMN_INSTALL_STAGING = YES
BRBOX_LIBADCMN_INSTALL_TARGET = YES
BRBOX_LIBADCMN_DEPENDENCIES = brbox_libAdSttngs json-c
$(eval $(cmake-package))

