#!/bin/sh
#
# Set default hostname if desnt exist
#
start() {
	echo -n "Checking default hostname: "
	default-hostname -f n
	echo "OK"
}

stop() {
	echo -n "Unchecking default hostname: "
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
